### ISSUE TITLE
version 1.1.12 crashes on a dedicated server

### ISSUE THREAD

**Issue by kerzenhans** [BeetoGuy/LevelUp2#27]
I can't start version 1.1.12 on a dedicated server.

googled 
net/minecraft/client/util/ITooltipFlag 

I found fixes with "@SideOnly(Side.CLIENT)" declarations where ITooltipFlag was used.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 12/7/17 6:04 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Level Up! Reloaded (levelup2)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:127)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:111)
	at levelup2.skills.SkillRegistry.postLoadSkills(SkillRegistry.java:102)
	at levelup2.LevelUp2.postInit(LevelUp2.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.13.9-1-ARCH
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2943699432 bytes (2807 MB) / 4032823296 bytes (3846 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 3 total; -Xms2G -Xmx7G -XX:ParallelGCThreads=4
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2556 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version          | Source                                      | Signature                                |
	|:----- |:-------------------- |:---------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft            | 1.12.2           | minecraft.jar                               | None                                     |
	| UCHIJ | mcp                  | 9.42             | minecraft.jar                               | None                                     |
	| UCHIJ | FML                  | 8.0.99.99        | forge-1.12.2-14.23.1.2556-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge                | 14.23.1.2556     | forge-1.12.2-14.23.1.2556-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | craftstudioapi       | 1.0.0            | CraftStudio-1.0.0.93-mc1.12-alpha.jar       | None                                     |
	| UCHIJ | animania             | 1.4.2            | animania-1.12.2-1.4.2.jar                   | None                                     |
	| UCHIJ | applecore            | 2.2.2            | AppleCore-mc1.12.2-2.2.2.jar                | None                                     |
	| UCHIJ | appliedenergistics2  | rv5-stable-3     | appliedenergistics2-rv5-stable-3.jar        | None                                     |
	| UCHIJ | architecturecraft    | @VERSION@        | architecturecraft-1.12-1.20.jar             | None                                     |
	| UCHIJ | astralsorcery        | 1.8.2            | astralsorcery-1.12.2-1.8.2.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJ | bibliocraft          | 2.4.3            | BiblioCraft[v2.4.3][MC1.12.0].jar           | None                                     |
	| UCHIJ | openterraingenerator | v2               | OpenTerrainGenerator-1.12.2 - v2.jar        | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJ | biomebundle          | 5.1              | Biome_Bundle-1.12.2-v6.1.jar                | None                                     |
	| UCHIJ | chameleon            | 1.12-4.1.3       | Chameleon-1.12-4.1.3.jar                    | None                                     |
	| UCHIJ | codechickenlib       | 3.1.3.313        | CodeChickenLib-1.12-3.1.3.313-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | mantle               | 1.12-1.3.1.21    | Mantle-1.12-1.3.1.21.jar                    | None                                     |
	| UCHIJ | jei                  | 4.8.5.133        | jei_1.12.2-4.8.5.133.jar                    | None                                     |
	| UCHIJ | tconstruct           | 1.12-2.7.4.34    | TConstruct-1.12-2.7.4.34.jar                | None                                     |
	| UCHIJ | p455w0rdslib         | 2.0.24           | p455w0rdslib-1.12-2.0.24.jar                | None                                     |
	| UCHIJ | danknull             | 1.0.14           | DankNull-1.12-1.0.14.jar                    | None                                     |
	| UCHIJ | enderstorage         | 2.4.0.122        | EnderStorage-1.12-2.4.0.122-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | extrautils2          | 1.0              | extrautils2-1.12-1.6.8.jar                  | None                                     |
	| UCHIJ | ftbl                 | 4.2.5            | FTBLib-4.2.5.jar                            | None                                     |
	| UCHIJ | ftbu                 | 4.2.4            | FTBUtilities-4.2.4.jar                      | None                                     |
	| UCHIJ | gargoyles            | 1                | Gargoyles mod 1.12.2 patch 1.jar            | None                                     |
	| UCHIJ | hopperducts          | 1.5              | hopperducts-mc1.12-1.5.jar                  | None                                     |
	| UCHIJ | waila                | 1.8.23           | Hwyla-1.8.23-B38_1.12.jar                   | None                                     |
	| UCHIJ | journeymap           | 1.12.2-5.5.2     | journeymap-1.12.2-5.5.2.jar                 | None                                     |
	| UCHIJ | leafdecay            | 1.0.0.2          | leafdecay-1.0.0.2-mc1.12.2.jar              | None                                     |
	| UCHIE | levelup2             | ${version}       | Level Up! 2-1.1.12-1.12.jar                 | None                                     |
	| UCHIJ | mekanism             | 9.4.2            | Mekanism-1.12.2-9.4.2.327.jar               | None                                     |
	| UCHIJ | mekanismgenerators   | 9.4.2            | MekanismGenerators-1.12.2-9.4.2.327.jar     | None                                     |
	| UCHIJ | mekanismtools        | 9.4.2            | MekanismTools-1.12.2-9.4.2.327.jar          | None                                     |
	| UCHIJ | mercurius_updater    | 1.0              | MercuriusUpdater-1.12.2.jar                 | None                                     |
	| UCHIJ | minecoprocessors     | 1.12.2-4         | minecoprocessors-1.12.2-4.jar               | None                                     |
	| UCHIJ | nex                  | 2.1.14.15        | NetherEx-1.12-2.1.14.15.jar                 | None                                     |
	| UCHIJ | netherportalfix      | 5.3.13           | NetherPortalFix_1.12.1-5.3.13.jar           | None                                     |
	| UCHIJ | openglider           | @VERSION@        | OpenGlider-1.12.1-1.1.0.jar                 | None                                     |
	| UCHIJ | xreliquary           | 1.12.2-1.3.4.724 | Reliquary-1.12.2-1.3.4.724.jar              | None                                     |
	| UCHIJ | sentek               | 1.8              | sentek-1.8.jar                              | None                                     |
	| UCHIJ | signpost             | 1.06.1           | signpost-1.12-1.06.1.jar                    | None                                     |
	| UCHIJ | solcarrot            | 1.2.0            | solcarrot-1.12.1-1.2.0.jar                  | None                                     |
	| UCHIJ | storagedrawers       | 1.12-5.2.5       | StorageDrawers-1.12.1-5.3.3.jar             | None                                     |
	| UCHIJ | tombstone            | 2.0.0-beta       | tombstone-2.0.0-beta-1.12.jar               | None                                     |
	| UCHIJ | toroquest            | 1.12.1-5.2       | toroquest-1.12.1-5.2.jar                    | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
AstralCore (astralsorcery-1.12.2-1.8.2.jar)
  
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by BeetoGuy** [comment]
I had a feeling that I should have made it clientside only, and once again, I was proven right after second-guessing myself.
