### ISSUE TITLE
Specialisation menu reappears, doesn't save

### ISSUE THREAD

**Issue by loudwhitenoise** [BeetoGuy/LevelUp2#29]
I was previously using the mod perfectly fine, spent a few levels on things. Then I updated a pile of things, and I *believe* it was the Forge update that broke it. You see, I have the crafting specialisation active, but opening the menu asks me to choose a class again. I still have the abilities from my levels, even though I can't activate any further ones.

I think this part of the log is relevant.

`[17:08:06] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
	at levelup2.network.SkillPacketHandler.lambda$onServerPacket$0(SkillPacketHandler.java:58) ~[SkillPacketHandler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
`

**Comment by BeetoGuy** [comment]
I've heard Forge broke a lot of things lately. I don't even know what I can change on my end. _If_ I can change anything.

**Comment by primetoxinz** [comment]
It might be too late but do you know what forge you were in before and after this issue arose?

**Comment by BeetoGuy** [comment]
A mod list will also be helpful, I can't replicate it period.

**Comment by BeetoGuy** [comment]
Confirmed to be an issue on Forge's end, update to their latest build.
