### ISSUE TITLE
Server crash FurnaceEfficiencyBonus 1.12.2

### ISSUE THREAD

**Issue by AdaraChristine** [BeetoGuy/LevelUp2#40]
Level Up! 2-1.1.17-1.12
Forge 1.12.2-14.23.2.2611

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at levelup2.skills.crafting.FurnaceEfficiencyBonus.lambda$doFurnaceTicks$0(FurnaceEfficiencyBonus.java:119)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at levelup2.skills.crafting.FurnaceEfficiencyBonus.doFurnaceTicks(FurnaceEfficiencyBonus.java:119)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1280_FurnaceEfficiencyBonus_doFurnaceTicks_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

https://pastebin.com/1n8qxPRF

**Comment by AdaraChristine** [comment]
Im still getting this error.
Forge 14.23.2.2611
Level Up! 2-1.1.18-1.12

Time: 3/29/18 12:42 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at levelup2.skills.crafting.FurnaceEfficiencyBonus.lambda$doFurnaceTicks$0(FurnaceEfficiencyBonus.java:119)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at levelup2.skills.crafting.FurnaceEfficiencyBonus.doFurnaceTicks(FurnaceEfficiencyBonus.java:119)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1288_FurnaceEfficiencyBonus_doFurnaceTicks_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
https://pastebin.com/56TPa7K6

**Comment by BeetoGuy** [comment]
After asking around, the only possibility is that something is pushing a null entry into the tile entity list. Which honestly shouldn't happen in any case, and there's no real way I can think of to replicate those conditions.
