### ISSUE TITLE
Need help on custom Ore Chunks for Prospecting

### ISSUE THREAD

**Issue by Heaveness** [BeetoGuy/LevelUp2#81]
Need assistant on how to add in custom ore chunks for the prospecting skill. Here is my config file:
`    # Ores that split into chunks. (String build: Ore name, color, experience yield, smelting result (mod:item:metadata:stacksize), chunk name, (optional) defined chunk [default: ]
    S:endores <

     >

    # Ores that split into chunks. (String build: Ore name, color, experience yield, smelting result (mod:item:metadata:stacksize), chunk name, (optional) defined chunk [default: [oreQuartz,0xE5DED5,2,minecraft:quartz,Nether Quartz], [oreCobalt,0x2979e7,4,tconstruct:ingots,Cobalt], [oreArdite,0xFFBD24,5,tconstruct:ingots:1,Ardite]]
    S:netherores <
        oreQuartz,0xE5DED5,2,minecraft:quartz,Nether Quartz
     >

    # Ores that split into chunks. (String build: Ore name, color, experience yield, smelting result (mod:item:metadata:stacksize), chunk name, (optional) defined chunk [default: [oreCoal,0x343434,1,minecraft:coal,Coal], [oreIron,0xBC9980,1,minecraft:iron_ingot,Iron], [oreGold,0xFCEE4B,2,minecraft:gold_ingot,Gold], [oreDiamond,0x5DECF5,4,minecraft:diamond,Diamond], [oreEmerald,0x17DD62,4,minecraft:emerald,Emerald], [oreRedstone,0xFF0000,2,minecraft:redstone,Redstone], [oreLapis,0x193CB4,2,minecraft:dye:4,Lapis], [oreCopper,0xFF6D11,1,thermalfoundation:material:128,Copper], [oreTin,0x8FB0CE,1,thermalfoundation:material:129,Tin], [oreSilver,0xA9CDDC,2,thermalfoundation:material:130,Silver], [oreLead,0x515C73,2,thermalfoundation:material:131,Lead], [oreAluminum,0xE2CEE1,2,thermalfoundation:material:132,Aluminum], [oreNickel,0xAAA37B,2,thermalfoundation:material:133,Nickel], [orePlatinum,0xA1DCFF,3,thermalfoundation:material:134,Platinum], [oreIridium,0xB7BFDC,4,thermalfoundation:material:135,Iridium], [oreMithril,0x64B9D8,4,thermalfoundation:material:136,Mana-Infused]]
    S:surfaceores <
        oreCoal,0x343434,1,minecraft:coal,Coal
        oreIron,0xBC9980,1,minecraft:iron_ingot,Iron
        oreGold,0xFCEE4B,2,minecraft:gold_ingot,Gold
        oreDiamond,0x5DECF5,4,minecraft:diamond,Diamond
        oreEmerald,0x17DD62,4,minecraft:emerald,Emerald
        oreRedstone,0xFF0000,2,minecraft:redstone,Redstone
        oreLapis,0x193CB4,2,minecraft:dye:4,Lapis
        oreCopper,0xFF6D11,1,thermalfoundation:material:128,Copper
        oreTin,0x8FB0CE,1,thermalfoundation:material:129,Tin
        oreSilver,0xA9CDDC,2,thermalfoundation:material:130,Silver
        oreMithril,0x64B9D8,4,thermalfoundation:material:136,Mythril
	oreAstralStarmetal,0xF3F3F3,3,astralsorcery:itemcraftingcomponent:1,Starmetal
	oreAdamantine,0x00FF00,3,simpleores:adamantium_ingot,Viridium
     >

whitelist {
    # Blocks that don't have their own OreDict entry, but still drop registered ores. [default: [geolosys:ore_vanilla], [geolosys:ore]]
    S:"Special ore cases" <
        geolosys:ore_vanilla
        geolosys:ore
     >

`

It looks like I am doing it right from the examples you have given. But whenever I am trying to loading the game, it crashes. This will occur in the crash-report.

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Level Up! Reloaded (levelup2)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at levelup2.config.LevelUpConfig.assembleOreChunks(LevelUpConfig.java:104)
    at levelup2.config.LevelUpConfig.init(LevelUpConfig.java:82)
    at levelup2.LevelUp2.preInit(LevelUp2.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

Would really love a help on this...

**Comment by BeetoGuy** [comment]
Looks like it's the end ores field doing it. I'd delete the end ores section and let that regenerate to see if that solves it.

**Comment by Heaveness** [comment]
I was able to fix this problem thanks to another nice guy. I realized I got the wrong oreDictionary term for Adamantium. It was oreAdamantium, not oreAdamantine. Sorry for all the troubles. D:
