### ISSUE TITLE
Client method being called on server side

### ISSUE THREAD

**Issue by Sir-Will** [BeetoGuy/LevelUp2#93]
Version 1.2.4
```
java.lang.NoSuchMethodError: levelup2.event.CapabilityEventHandler.getDivisor(Lnet/minecraft/util/ResourceLocation;)D
    at levelup2.event.CraftingSkillHandler.doCropDrops(CraftingSkillHandler.java:150)
    at levelup2.event.CraftingSkillHandler.onBlockBroken(CraftingSkillHandler.java:141)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2200_CraftingSkillHandler_onBlockBroken_BreakEvent.invoke(.dynamic)
```

**Comment by BeetoGuy** [comment]
Not exactly a client method, it's a method that was introduced in 1.5.0. Really don't understand how Level Up 1.2.4 would be calling a method that doesn't exist.
